eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
  instance:
    hostname: getway-client
    prefer-ip-address: true
spring:
  application:
    name: getway-client
  rabbitmq:
          host: 39.105.53.166
          port: 5672
          username: breamer
          password: beyond1983ju
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user-client
          predicates:
            - Path=/user-client/**
          filters:
            - StripPrefix=0
            - SwaggerHeaderFilter
            - UserClientPostFilter
            - UserClientPreFilter
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/fallback
        - id: product
          uri: lb://product-client
          predicates:
           - Path=/product-client/**
          filters:
            - StripPrefix=0
            - SwaggerHeaderFilter
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/fallback
        - id: order
          uri: lb://order-client
          predicates:
            - Path=/order-client/**
          filters:
            - StripPrefix=0
            - SwaggerHeaderFilter
            - UserClientPostFilter
            - UserClientPreFilter
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/fallback
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true
server:
  port: 8888

