eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
  instance:
    hostname: user-client
    prefer-ip-address: true
#  cloud:
#      config:
#        discovery:
#          enabled: true
#          service-id: CONFIG-SERVER
#        profile: dev
#        label: release
server:
  servlet:
    context-path: /user-client
  port: 8083
spring:
  application:
    name: user-client
  zipkin:
      base-url: http://39.105.53.166:9411/
      sender:
        type: web
  sleuth:
      sampler:
        probability: 1
feign:
  hystrix:
    enabled: true