spring:
  application:
      name: product-client
  zipkin:
      base-url: http://39.105.53.166:9411/
      sender:
        type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    username: root
    password: uboat!1214
    url: jdbc:mysql://39.105.53.166:3306/breamer_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    exceptionSorter: true
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  jpa:
    show-sql: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  rabbitmq:
    host: 39.105.53.166
    port: 5672
    username: breamer
    password: beyond1983ju
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
  instance:
    hostname: product-client
    prefer-ip-address: true
server:
  servlet:
    context-path: /product-client
  port: 8082
product:
  port: 8082
#spring:
#  zipkin:
#      base-url: http://39.105.53.166:9411/
#      sender:
#        type: web
#  # 服务抽样频率 1 - 100%
##  sleuth:
##    sampler:
##      probability: 1
#  datasource:
#    username: root
#    password: uboat!1214
#    url: jdbc:mysql://39.105.53.166:3306/breamer_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    exceptionSorter: true
#    testOnReturn: false
#    poolPreparedStatements: true
#    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#    useGlobalDataSourceStat: true
#  jpa:
#    show-sql: true
#    database: mysql
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#  rabbitmq:
#    host: 39.105.53.166
#    port: 5672
#    username: breamer
#    password: beyond1983ju
#server:
#  port: 8082